services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-petclinic}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-petclinic}
      - POSTGRES_DB=${POSTGRES_DB:-petclinic}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
