# database init, supports mysql too
database=mysql
spring.datasource.url=jdbc:mysql://localhost/smartcheckin
spring.datasource.username=${MYSQL_USER:smartcheckin}
spring.datasource.password=${MYSQL_PASSWORD:smartcheckin}
# SQL is written to be idempotent so this is safe
spring.datasource.initialization-mode=always
