# database init, supports mysql too
database=mysql
spring.datasource.url=jdbc:mysql://localhost/smartcheckin
spring.datasource.username=smartcheckin
spring.datasource.password=smartcheckin
# SQL is written to be idempotent so this is safe
spring.datasource.initialization-mode=always
