# database init, supports mysql too
database=mysql
spring.datasource.url=jdbc:mysql://localhost/badistributionacademy
spring.datasource.username=${MYSQL_USER:badistributionacademy}
spring.datasource.password=${MYSQL_PASSWORD:badistributionacademy}
# SQL is written to be idempotent so this is safe
spring.datasource.initialization-mode=always
