# PostgreSQL settings
spring.datasource.url=jdbc:postgresql://localhost:5432/smartcheckin
spring.datasource.username=${POSTGRES_USER:checkin_user}
spring.datasource.password=${POSTGRES_PASSWORD:checkin_secret_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# Init DB
spring.sql.init.mode=always
spring.sql.init.platform=postgres

# Configuración de límites para la subida de ficheros (Multipart)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=8MB